const fs = require('fs');

const tsFile = 'src/app/components/admin-dashboard/admin-dashboard.component.ts';
let ts = fs.readFileSync(tsFile, 'utf8');

ts = ts.replace(
  `  openConfirmBookingModal(client: any) {\r\n    this.confirmBookingData = {\r\n      clientId: client.id,\r\n      hoardingName: client.hoarding_name,\r\n      occupied_till: ''\r\n    };\r\n    this.isConfirmBookingModalOpen = true;\r\n  }`,
  `  openConfirmBookingModal(client: any) {\r\n    this.confirmBookingData = {\r\n      clientId: client.id,\r\n      hoardingName: client.hoarding_name,\r\n      action: 'confirm',\r\n      occupied_till: ''\r\n    };\r\n    this.isConfirmBookingModalOpen = true;\r\n  }`
);

ts = ts.replace(
  `  submitConfirmBooking() {\r\n    if (!this.confirmBookingData.occupied_till) {\r\n      alert("Please select an 'Occupied Till' date.");\r\n      return;\r\n    }\r\n    this.apiService.confirmBooking(this.confirmBookingData.clientId, { occupied_till: this.confirmBookingData.occupied_till }).subscribe({\r\n      next: (res: any) => {\r\n        this.notifications.unshift(res.message);\r\n        this.showNotifications = true;\r\n        setTimeout(() => { this.showNotifications = false; }, 5000);\r\n        this.fetchHoardings();\r\n        this.closeConfirmBookingModal();\r\n      },\r\n      error: (e) => {\r\n        console.error(e);\r\n        alert(e.error?.message || 'Failed to confirm booking.');\r\n      }\r\n    });\r\n  }`,
  `  submitConfirmBooking() {\r\n    if (this.confirmBookingData.action === 'confirm') {\r\n      if (!this.confirmBookingData.occupied_till) {\r\n        alert("Please select an 'Occupied Till' date.");\r\n        return;\r\n      }\r\n      this.apiService.confirmBooking(this.confirmBookingData.clientId, { occupied_till: this.confirmBookingData.occupied_till }).subscribe({\r\n        next: (res: any) => {\r\n          this.notifications.unshift(res.message);\r\n          this.showNotifications = true;\r\n          setTimeout(() => { this.showNotifications = false; }, 5000);\r\n          this.fetchHoardings();\r\n          this.fetchClients();\r\n          this.closeConfirmBookingModal();\r\n        },\r\n        error: (e) => {\r\n          console.error(e);\r\n          alert(e.error?.message || 'Failed to confirm booking.');\r\n        }\r\n      });\r\n    } else {\r\n      this.apiService.updateClientStatus(this.confirmBookingData.clientId, 'UNDER REVIEW').subscribe({\r\n        next: (res: any) => {\r\n          this.notifications.unshift('Booking marked as Under Review.');\r\n          this.showNotifications = true;\r\n          setTimeout(() => { this.showNotifications = false; }, 5000);\r\n          this.fetchClients();\r\n          this.closeConfirmBookingModal();\r\n        },\r\n        error: (e) => {\r\n          console.error(e);\r\n          alert(e.error?.message || 'Failed to update status.');\r\n        }\r\n      });\r\n    }\r\n  }`
);

fs.writeFileSync(tsFile, ts);

const htmlFile = 'src/app/components/admin-dashboard/admin-dashboard.component.html';
let html = fs.readFileSync(htmlFile, 'utf8');

html = html.replace(
  `                <th>Interested In</th>\r\n                <th>Status</th>`,
  `                <th>Interested In</th>\r\n                <th>Booking</th>\r\n                <th>Status</th>`
);

html = html.replace(
  `                  <span *ngIf="!c.hoarding_name" style="color:#9ca3af; font-size:12px;">-</span>\r\n                </td>\r\n                <td><span class="text-green"`,
  `                  <span *ngIf="!c.hoarding_name" style="color:#9ca3af; font-size:12px;">-</span>\r\n                </td>\r\n                <td>\r\n                  <button *ngIf="c.hoarding_name" type="button" class="btn-sm" style="padding: 4px 10px; font-size: 12px; border-radius: 4px; border: 1px solid #d1d5db; background: #f3f4f6; color: #374151; font-weight: 500; cursor: pointer;" (click)="openConfirmBookingModal(c)">Update</button>\r\n                </td>\r\n                <td><span class="text-green"`
);

const oldModal = `      <!-- Confirm Booking Modal -->\r\n      <div class="modal-overlay" *ngIf="isConfirmBookingModalOpen">\r\n        <div class="modal-content" style="width: 450px;">\r\n          <div class="modal-header">\r\n            <h3>Confirm Purchase</h3>\r\n            <button class="close-btn" (click)="closeConfirmBookingModal()"><i class='bx bx-x'></i></button>\r\n          </div>\r\n          <div class="modal-body">\r\n            <p style="margin-bottom: 20px; color: #4b5563; font-size: 14px;">\r\n              Mark <strong>{{ confirmBookingData.hoardingName }}</strong> as occupied? This will update the billboard's status on the main site.\r\n            </p>\r\n            <form (ngSubmit)="submitConfirmBooking()">\r\n              <div class="form-group full-width" style="margin-bottom: 20px;">\r\n                <label>Occupied Till *</label>\r\n                <input type="date" name="occupied_till" [(ngModel)]="confirmBookingData.occupied_till" required style="width: 100%; padding: 8px; border: 1px solid #d1d5db; border-radius: 4px;">\r\n              </div>\r\n              <div style="display: flex; gap: 10px; justify-content: flex-end;">\r\n                <button type="button" (click)="closeConfirmBookingModal()" style="padding: 8px 15px; border: 1px solid #d1d5db; background: transparent; border-radius: 4px; cursor: pointer;">Cancel</button>\r\n                <button type="submit" class="action-btn-green" style="padding: 8px 15px;">Confirm Payment</button>\r\n              </div>\r\n            </form>\r\n          </div>\r\n        </div>\r\n      </div>`;

const newModal = `      <!-- Confirm Booking Modal -->\r\n      <div class="modal-overlay" *ngIf="isConfirmBookingModalOpen">\r\n        <div class="modal-content" style="width: 450px;">\r\n          <div class="modal-header">\r\n            <h3>Booking Status</h3>\r\n            <button class="close-btn" (click)="closeConfirmBookingModal()"><i class='bx bx-x'></i></button>\r\n          </div>\r\n          <div class="modal-body">\r\n            <p style="margin-bottom: 20px; color: #4b5563; font-size: 14px;">\r\n              Update booking status for <strong>{{ confirmBookingData.hoardingName || 'Lead' }}</strong>.\r\n            </p>\r\n            <form (ngSubmit)="submitConfirmBooking()">\r\n              <div class="form-group full-width" style="margin-bottom: 20px;">\r\n                <label>Action *</label>\r\n                <select name="action" [(ngModel)]="confirmBookingData.action" required style="width: 100%; padding: 8px; border: 1px solid #d1d5db; border-radius: 4px;">\r\n                  <option value="confirm">Confirm Booking</option>\r\n                  <option value="review">Under Review</option>\r\n                </select>\r\n              </div>\r\n              <div class="form-group full-width" *ngIf="confirmBookingData.action === 'confirm'" style="margin-bottom: 20px;">\r\n                <label>Occupied Till *</label>\r\n                <input type="date" name="occupied_till" [(ngModel)]="confirmBookingData.occupied_till" required style="width: 100%; padding: 8px; border: 1px solid #d1d5db; border-radius: 4px;">\r\n              </div>\r\n              <div style="display: flex; gap: 10px; justify-content: flex-end;">\r\n                <button type="button" (click)="closeConfirmBookingModal()" style="padding: 8px 15px; border: 1px solid #d1d5db; background: transparent; border-radius: 4px; cursor: pointer;">Cancel</button>\r\n                <button type="submit" class="action-btn-green" style="padding: 8px 15px;">Submit</button>\r\n              </div>\r\n            </form>\r\n          </div>\r\n        </div>\r\n      </div>`;

html = html.replace(oldModal, newModal);
fs.writeFileSync(htmlFile, html);

console.log("Done");
